#tomcat的端口号
#项目的项目名,以后我们访问该项目http://ip:port/context-path
#http://localhost:8989/SpringBootDemo1
server:
  port: 8989
  servlet:
    context-path: /SpringBootDemo2
#配置数据库的连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#给实体起别名，设置映射文件的路径。
mybatis:
  type-aliases-package: com.xuchao.entity
  mapper-locations: classpath:com/xuchao/mapper/*.xml
#实现分页
pagehelper:
  helper-dialect: mysql
  reasonable: true #分页合理化
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数